@startuml

title __SERVICE's Class Diagram__\n

  namespace  {
    namespace om.adobe.prj {
      namespace service {
        class com.adobe.prj.service.ClientService {
            - clientDao : ClientDao
            - projectDao : ProjectDao
            + addClient()
            + deleteClient()
            + getClient()
            + getClients()
            + updateClient()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace service {
        class com.adobe.prj.service.DocumentService {
            - documentDao : DocumentDao
            - projectDao : ProjectDao
            + addDocument()
            + deleteDocument()
            + findDocumentsByDocName()
            + findDocumentsById()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace service {
        class com.adobe.prj.service.EmployeeService {
            - employeeDao : EmployeeDao
            - passwordEncryptor : BasicPasswordEncryptor
            + addEmployee()
            + deleteEmployee()
            + getEmployee()
            + getEmployeeByEmail()
            + getEmployees()
            + updatePassword()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace service {
        class com.adobe.prj.service.ExpenseService {
            - expenseDao : ExpenseDao
            + addExpense()
            + deleteExpense()
            + deleteExpenses()
            + getAllExpense()
            + getExpense()
            + getExpenseByEmplyoeeId()
            + getExpenseByProject()
            + getExpenseByStatus()
            + getExpenseByStatusforProject()
            + getExpenseTotal()
            + paginateExpense()
            + updateExpense()
            + updateExpenseStatus()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace service {
        class com.adobe.prj.service.ProjectService {
            - clientDao : ClientDao
            - documentDao : DocumentDao
            - employeeDao : EmployeeDao
            - projectDao : ProjectDao
            + addProject()
            + deleteProject()
            + deleteProjects()
            + getAllProjects()
            + getProject()
            + getProjectsByUser()
            + isProjectAccessible()
            + updateProject()
            + updateTags()
            + validateProject()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
