@startuml

title __API's Class Diagram__\n

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ClientControllerTest {
            - authenticationProvider : EmployeeAuthenticationProvider
            - clientService : ClientService
            - employeeService : EmployeeService
            - jwtTokenUtil : JwtUtil
            - mockMvc : MockMvc
            {static} + asJsonString()
            ~ shouldAddClient()
            ~ shouldDeleteClient()
            ~ shouldGetClientById()
            ~ shouldGetClients()
            ~ shouldUpdateClient()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.DocumentControllerTest {
            - authService : EmployeeAuthenticationProvider
            - clientService : ClientService
            - documentService : DocumentService
            - employeeService : EmployeeService
            - mockEmp : Employee
            - mockMvc : MockMvc
            - utilService : JwtUtil
            + deleteFromDBAccessDeniedExceptionTest()
            + deleteFromDBNotFoundExceptionTest()
            + deleteFromDBTest()
            + downloadFromDBAccessDeniedExceptionTest()
            + downloadFromDBNotFoundExceptionTest()
            + downloadFromDBTest()
            + initEach()
            + uploadToDBTest()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ExpenseControllerTest {
            - authenticationProvider : EmployeeAuthenticationProvider
            - clientService : ClientService
            - employeeService : EmployeeService
            - expenseService : ExpenseService
            - jwtTokenUtil : JwtUtil
            - mockMvc : MockMvc
            - projectService : ProjectService
            + addExpenseExceptionTest()
            + addExpenseTest()
            {static} + asJsonString()
            + deleteExpenseExceptionTest()
            + deleteExpenseTest()
            + deleteExpensessExceptionTest()
            + deleteExpensessTest()
            + getApprovalsByStatusTest()
            + getExpenseExceptionTest()
            + getExpenseTest()
            + getMyExpenseTest()
            + initEach()
            + updateExpenseExceptionTest()
            + updateExpenseExceptionTest2()
            + updateExpenseStatusExceptionTest1()
            + updateExpenseStatusExceptionTest2()
            + updateExpenseStatusTest()
            + updateExpenseTest()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.FrontControllerTest {
            - authenticationProvider : EmployeeAuthenticationProvider
            - employeeService : EmployeeService
            - employees : List<Employee>
            - jwtTokenUtil : JwtUtil
            - mockMvc : MockMvc
            {static} + asJsonString()
            ~ shouldAuthenticate()
            ~ shouldChangePassword()
            ~ shouldLogout()
            ~ shouldNotAuthenticate()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ProjectControllerTest {
            - authService : EmployeeAuthenticationProvider
            - clientService : ClientService
            - employeeService : EmployeeService
            - mockEmp : Employee
            - mockMvc : MockMvc
            - projectService : ProjectService
            - utilService : JwtUtil
            + addProjectBadRequestExceptionTest()
            + addProjectExceptionTest()
            + addProjectTest()
            + deleteProjectAccessDeniedExceptionTest()
            + deleteProjectNotFoundExceptionTest()
            + deleteProjectTest()
            + deleteProjectsAccessDeniedExceptionTest()
            + deleteProjectsNotFoundExceptionTest()
            + deleteProjectsTest()
            + getEmpProjectTest()
            + getProjectAccessDeniedExceptionTest()
            + getProjectNotFoundExceptionTest()
            + getProjectTest()
            + initEach()
            + updateProjectAccessDeniedExceptionTest()
            + updateProjectBadRequestExceptionTest()
            + updateProjectNotFoundExceptionTest()
            + updateProjectTest()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
