@startuml

title __API's Class Diagram__\n

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ClientController {
            - service : ClientService
            + addClient()
            + deleteClient()
            + getClient()
            + getClients()
            + updateClient()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.DocumentController {
            - documentService : DocumentService
            + deleteFromDB()
            + downloadFromDB()
            + uploadToDB()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.EmployeeController {
            - service : EmployeeService
            + addEmployee()
            + getEmployees()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ExpenseController {
            - expenseService : ExpenseService
            - projectService : ProjectService
            + addExpense()
            + deleteExpense()
            + deleteExpenses()
            + getApprovalsByStatus()
            + getExpense()
            + getExpenseByProject()
            + getExpenseTotal()
            + getMyExpense()
            + updateExpense()
            + updateExpenseStatus()
            ~ getEmployee()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.FrontController {
            - authenticationProvider : EmployeeAuthenticationProvider
            - employeeService : EmployeeService
            - jwtTokenUtil : JwtUtil
            + authenticate()
            + createAuthenticationToken()
            + logout()
            + updatePassword()
        }
      }
    }
  }
  

  namespace  {
    namespace om.adobe.prj {
      namespace api {
        class com.adobe.prj.api.ProjectController {
            - projectService : ProjectService
            + addProject()
            + deleteProject()
            + deleteProjects()
            + getEmpProjects()
            + getProject()
            + updateProject()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
